In [2]:
# importing module
from pandas import *

# reading CSV file
data = read_csv("company_sales_data.csv")

data

C:\Users\admin\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\admin\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700
10,11,2340,2100,7300,13300,2400,2100,41280,412800
11,12,2900,1760,7400,14400,1800,1760,30020,300200

In [3]:
data.head(10)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700

In [4]:
data.tail(5)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700
10,11,2340,2100,7300,13300,2400,2100,41280,412800
11,12,2900,1760,7400,14400,1800,1760,30020,300200

In [5]:
month = data['month_number']
month

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
Name: month_number, dtype: int64

In [6]:
# converting column data to list
month = data['month_number'].tolist()
month

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [7]:
fc = data['facecream'].tolist()
print('Facecream:', fc)

Facecream: [2500, 2630, 2140, 3400, 3600, 2760, 2980, 3700, 3540, 1990, 2340, 2900]

In [16]:
fw = data['facewash'].tolist()
tp = data['toothpaste'].tolist()
sh = data['shampoo'].tolist()

# printing list data
print('Facewash:', fw)
print('Toothpaste:', tp)
print('Shampoo:', sh)

Facewash: [1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760]
Toothpaste: [5200, 5100, 4550, 5870, 4560, 4890, 4780, 5860, 6100, 8300, 7300, 7400]
Shampoo: [1200, 2100, 3550, 1870, 1560, 1890, 1780, 2860, 2100, 2300, 2400, 1800]

# Method 2

In [27]:
# importing the module
import csv

# open the file in read mode
filename = open('company_sales_data.csv', 'r')

# creating dictreader object
file = csv.DictReader(filename)
file

In [28]:
# creating empty lists
month = []
totalprofit = []
totalunit = []

# iterating over each row and append
# values to empty list
for col in file:
	month.append(col['month_number'])
	totalprofit.append(col['moisturizer'])
	totalunit.append(col['total_units'])

# printing lists
print('Month:', month)
print('Moisturizer:', totalprofit)
print('Total Units:', totalunit)

Month: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
Moisturizer: ['1500', '1200', '1340', '1130', '1740', '1555', '1120', '1400', '1780', '1890', '2100', '1760']
Total Units: ['21100', '18330', '22470', '22270', '20960', '20140', '29550', '36140', '23400', '26670', '41280', '30020']

# Create a csv file

In [43]:
import csv

with open('employee.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    field = ["name", "age", "country"]
    
    writer.writerow(field)
    writer.writerow(["Oladele Damilola", "40", "Nigeria"])
    writer.writerow(["Alina Hricko", "23", "Ukraine"])
    writer.writerow(["Isabel Walter", "50", "United Kingdom"])

# Method 2

In [47]:
import csv

with open('employee1.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    row_list = [
        ["name", "age", "country"], 
        ["Oladele Damilola", "40", "Nigeria"], 
        ["Alina Hricko", "23" "Ukraine"], 
        ["Isabel Walter", "50" "United Kingdom"],
    ]
    
    writer.writerows(row_list)

To create all data in single row...

In [49]:
import csv

with open('employee2.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    row_list = [
        ["name", "age", "country"], 
        ["Oladele Damilola", "40", "Nigeria"], 
        ["Alina Hricko", "23" "Ukraine"], 
        ["Isabel Walter", "50" "United Kingdom"],
    ]
    
    writer.writerow(row_list)

# Json File

In [50]:
import json

# Data to be written
dictionary = {
	"name": "sathiyajith",
	"rollno": 56,
	"cgpa": 8.6,
	"phonenumber": "9976770500"
}

# Serializing json
json_object = json.dumps(dictionary, indent=4)

# Writing to sample.json
with open("sample.json", "w") as outfile:
	outfile.write(json_object)

Method 2: Writing JSON to a file in Python using json.dump() 
Another way of writing JSON to a file is by using json.dump() method The JSON package has the “dump” function which directly writes the dictionary to a file in the form of JSON, without needing to convert it into an actual JSON object. It takes 2 parameters:

dictionary – the name of a dictionary which should be converted to a JSON object.
file pointer – pointer of the file opened in write or append mode.

In [52]:
# Python program to write JSON
# to a file


import json

# Data to be written
dictionary = {
	"name": "sathiyajith",
	"rollno": 56,
	"cgpa": 8.6,
	"phonenumber": "9976770500"
}

with open("sample1.json", "w") as outfile:
	json.dump(dictionary, outfile)

# Parquet File

# How to write a DataFrame to a Parquet file in Python

Apache Parquet is a column-oriented, open-source data file format for data storage and retrieval. It offers high-performance data compression and encoding schemes to handle large amounts of complex data.

We use the to_parquet() method in Python to write a DataFrame to a Parquet file.

Syntax:
DataFrame.to_parquet(path=None, engine='auto', compression='snappy', index=None, partition_cols=None, storage_options=None, **kwargs)

Parameters:
path: This is the path to the Parquet file.
engine: This parameter indicates which Parquet library to use. The available options are auto, pyarrow, and fastparquet.
compression: This parameter indicates the type of compression to use. The available options are snappy, gzip, and brotli. The default compression is snappy.
index: This is a boolean parameter. If True, the DataFrame’s indexes are written to the file. If False, the indexes are ignored.
partition_cols: These are the names of the columns that partition the DataFrame. The order in which the columns are given determines the order in which they are partitioned.
storage_options: These are the extra options for a certain storage connection, such as a host, port, username, password, and so on.

In [67]:
import pandas as pd
import os

data = [['dom', 10], ['abhi', 15], ['celeste', 14]]

df = pd.DataFrame(data, columns = ['Name', 'Age'])

df.to_parquet("dataframe.parquet")

print("Listing the contents of the current directory:")
print(os.listdir('.'))

Listing the contents of the current directory:
['.ipynb_checkpoints', 'company_sales_data.csv', 'DataEngg_1.ipynb', 'dataframe.parquet', 'employee.csv', 'employee1.csv', 'employee2.csv', 'LT.jpg', 'lt2.png', 'sample.json', 'sample1.json']

In [66]:
pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-2024.5.0-cp39-cp39-win_amd64.whl.metadata (4.3 kB)
Collecting pandas>=1.5.0 (from fastparquet)
  Downloading pandas-2.2.2-cp39-cp39-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\admin\anaconda3\lib\site-packages (from fastparquet) (1.25.1)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.8.3-cp39-none-win_amd64.whl.metadata (4.3 kB)
Requirement already satisfied: fsspec in c:\users\admin\anaconda3\lib\site-packages (from fastparquet) (2022.7.1)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from fastparquet) (21.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas>=1.5.0->fastparquet) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas>=1.5.0->fastparquet) (2022.1)
Collecting tzdata>=2022.7 (from pandas>=1.5.0->fastparquet)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\admin\anaconda3\lib\site-packages (from packaging->fastparquet) (3.0.9)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.16.0)
Downloading fastparquet-2024.5.0-cp39-cp39-win_amd64.whl (672 kB)
   -------------------------------------- 672.6/672.6 kB 596.6 kB/s eta 0:00:00
Downloading cramjam-2.8.3-cp39-none-win_amd64.whl (1.6 MB)
   ---------------------------------------- 1.6/1.6 MB 1.1 MB/s eta 0:00:00
Downloading pandas-2.2.2-cp39-cp39-win_amd64.whl (11.6 MB)
   ---------------------------------------- 11.6/11.6 MB 2.4 MB/s eta 0:00:00
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Installing collected packages: tzdata, cramjam, pandas, fastparquet
  Attempting uninstall: pandas
    Found existing installation: pandas 1.4.4
    Uninstalling pandas-1.4.4:
      Successfully uninstalled pandas-1.4.4
Successfully installed cramjam-2.8.3 fastparquet-2024.5.0 pandas-2.2.2 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\admin\anaconda3\Lib\site-packages\~andas'.
  You can safely remove it manually.