In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
! unzip /content/archive.zip

Archive:  /content/archive.zip
  inflating: winequality-red.csv

In [ ]:
data=pd.read_csv("/content/winequality-red.csv")

In [ ]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [ ]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
x=data.drop("quality",axis=1)
print(x)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076
1               7.8             0.880         0.00             2.6      0.098
2               7.8             0.760         0.04             2.3      0.092
3              11.2             0.280         0.56             1.9      0.075
4               7.4             0.700         0.00             1.9      0.076
...             ...               ...          ...             ...        ...
1594            6.2             0.600         0.08             2.0      0.090
1595            5.9             0.550         0.10             2.2      0.062
1596            6.3             0.510         0.13             2.3      0.076
1597            5.9             0.645         0.12             2.0      0.075
1598            6.0             0.310         0.47             3.6      0.067

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56
1                    25.0                  67.0  0.99680  3.20       0.68
2                    15.0                  54.0  0.99700  3.26       0.65
3                    17.0                  60.0  0.99800  3.16       0.58
4                    11.0                  34.0  0.99780  3.51       0.56
...                   ...                   ...      ...   ...        ...
1594                 32.0                  44.0  0.99490  3.45       0.58
1595                 39.0                  51.0  0.99512  3.52       0.76
1596                 29.0                  40.0  0.99574  3.42       0.75
1597                 32.0                  44.0  0.99547  3.57       0.71
1598                 18.0                  42.0  0.99549  3.39       0.66

      alcohol
0         9.4
1         9.8
2         9.8
3         9.8
4         9.4
...       ...
1594     10.5
1595     11.2
1596     11.0
1597     10.2
1598     11.0

[1599 rows x 11 columns]

In [ ]:
y=data["quality"]
print(y)

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [ ]:
sc=StandardScaler()

scaled_data=sc.fit_transform(x)
scaled_data

array([[-0.52835961,  0.96187667, -1.39147228, ...,  1.28864292,
        -0.57920652, -0.96024611],
       [-0.29854743,  1.96744245, -1.39147228, ..., -0.7199333 ,
         0.1289504 , -0.58477711],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.33117661,
        -0.04808883, -0.58477711],
       ...,
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.70550789,
         0.54204194,  0.54162988],
       [-1.39015528,  0.65462046, -0.77526673, ...,  1.6773996 ,
         0.30598963, -0.20930812],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.51112954,
         0.01092425,  0.54162988]])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(scaled_data,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1279, 11), (320, 11), (1279,), (320,))

In [ ]:
y.value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,accuracy_score

In [ ]:
linear=LinearRegression()

In [ ]:
linear.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=linear.predict(x_test)
y_pred

array([5.34666441, 5.05631345, 5.66446972, 5.46451484, 5.72518476,
       5.27928659, 5.03421667, 5.12623347, 5.74534288, 5.68665032,
       6.13959677, 5.23386892, 5.54991474, 5.25825299, 5.44810502,
       6.46828999, 5.15018088, 5.59105157, 6.5560658 , 5.32255751,
       5.3918385 , 5.19610791, 5.94475739, 6.36197631, 5.35484893,
       5.41907575, 6.36483321, 5.35121573, 5.172392  , 6.16987311,
       5.25263058, 5.50657406, 5.75422105, 5.39101712, 5.45331031,
       5.02757499, 6.16173243, 5.68661555, 5.6486077 , 6.165471  ,
       5.52872593, 5.24414488, 6.17724727, 5.16500868, 5.87598332,
       5.81317121, 6.41982782, 5.6059474 , 5.15232137, 5.55634632,
       5.16044852, 5.10449459, 5.58371721, 6.33425313, 4.95134985,
       4.98364804, 6.01041999, 5.40809804, 5.83802638, 5.2486897 ,
       5.60717482, 5.96630957, 5.27619063, 5.30380113, 6.4949309 ,
       5.42033967, 6.34273471, 5.24618531, 6.41317317, 5.31237924,
       6.41746963, 4.74315748, 5.79362039, 5.8283184 , 6.17598768,
       5.29723707, 6.76198733, 5.89745261, 6.07833712, 6.43522754,
       5.29499011, 6.4546625 , 5.45007864, 5.69644693, 5.72368681,
       6.41233601, 5.31025119, 5.84548953, 6.31433877, 5.20585049,
       6.10141578, 5.70349712, 5.78679322, 5.93173502, 5.1852885 ,
       5.74819506, 5.17351769, 5.69336056, 4.99158806, 5.52004223,
       5.06867029, 5.13831807, 5.84991801, 5.72612872, 5.47766711,
       6.12476389, 5.73551897, 5.44180611, 6.08785125, 5.24667513,
       6.68434941, 5.26499691, 6.15359147, 4.74493131, 5.82508834,
       5.9872331 , 6.17033538, 5.50859099, 5.02156367, 5.83326942,
       6.21086737, 5.26363047, 5.75354145, 5.38942262, 5.39641713,
       5.25966957, 6.21024761, 5.69536196, 5.58586923, 5.82155344,
       5.79362039, 5.14962195, 5.01142496, 6.34824026, 5.55634632,
       5.08213438, 5.05668453, 5.3517036 , 5.11920475, 5.66948552,
       6.01614582, 6.03912287, 6.2439487 , 5.48155178, 5.86335248,
       5.26302973, 6.06162683, 5.4041289 , 5.99869245, 5.06897434,
       5.70161041, 6.14167652, 5.11821365, 5.67658854, 5.79362039,
       6.0891404 , 5.22103588, 5.90134727, 5.48941228, 5.93412645,
       6.3118134 , 5.71785286, 6.13152024, 4.9898825 , 5.39143155,
       5.63146602, 4.70626967, 5.232132  , 5.04110749, 4.99137335,
       5.20669998, 5.11005631, 6.29652093, 5.48263655, 5.73380671,
       5.86096397, 6.11131909, 5.38204246, 5.39418516, 5.11161705,
       4.74487438, 6.34043215, 5.57642863, 6.52465957, 5.18100269,
       6.37846442, 5.39147732, 5.7435927 , 6.71436012, 5.48263655,
       5.42573746, 6.08035849, 5.6017508 , 6.52660959, 5.79174569,
       5.32807323, 4.92850887, 5.40669848, 5.49983794, 6.12476389,
       5.36974106, 5.78401123, 5.48534309, 5.02135392, 6.65592712,
       5.62370825, 4.83368748, 5.73347951, 5.68074781, 6.09738854,
       5.99258428, 5.16969289, 5.7770828 , 6.59697123, 6.37009025,
       5.77981876, 5.46465189, 5.19009343, 5.80517998, 5.30830978,
       5.09158113, 6.24863165, 6.33674607, 5.99341483, 5.16829696,
       4.81289689, 5.22265229, 6.44901207, 5.48931502, 5.31886287,
       5.5589884 , 5.04938167, 6.32905554, 5.98208683, 6.04415923,
       6.12476389, 5.37906696, 5.72368681, 4.795237  , 5.03676054,
       5.68938109, 5.01079638, 5.83995808, 6.13732216, 5.24782156,
       5.56627333, 6.00210169, 5.3626292 , 6.68219105, 5.11532126,
       5.78120835, 5.62454656, 5.31952796, 5.51514228, 5.20719665,
       5.13154551, 5.48620652, 5.85075029, 5.71919777, 6.80397753,
       6.20404528, 6.04410296, 5.38204246, 6.50598024, 5.85449947,
       6.30306847, 5.05268393, 4.92613186, 5.94872379, 6.32176541,
       5.18546252, 5.8361393 , 5.40120414, 5.17199122, 5.3095161 ,
       5.49911144, 5.66556707, 6.21315993, 6.22227229, 5.26433184,
       6.48967503, 4.95165562, 5.37197617, 5.49931461, 5.3577211 ,
       5.82641444, 4.97385804, 6.03912287, 5.03990278, 5.76144224,
       5.67870975, 6.57726748, 5.67261468, 5.5851728 , 4.92156862,
       6.38162382, 5.10784567, 6.30108784, 6.21224582, 6.50221084,
       5.51985221, 5.16412612, 6.23283235, 5.32903476, 5.25839032,
       5.32882382, 5.89753508, 5.92128255, 6.26545355, 6.57918909,
       5.55219907, 5.56483453, 5.51937934, 5.61558301, 5.39101712,
       5.68815279, 5.23225544, 5.2805354 , 6.2724663 , 5.19707213])

In [ ]:
r2=r2_score(y_test,y_pred)
r2

0.403180341279622

In [ ]:
mse=mean_squared_error(y_test,y_pred)
mse

0.39002514396395493

In [ ]:
rmse=np.sqrt(mse)
rmse

0.624519930798013

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn=KNeighborsClassifier()

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=knn.predict(x_test)

In [ ]:
acc=accuracy_score(y_test,y_pred)
acc

0.553125

In [ ]:
knn1=KNeighborsClassifier(n_neighbors=9,weights='distance')

In [ ]:
knn1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9, weights='distance')

In [ ]:
y_pred1=knn1.predict(x_test)

In [ ]:
acc=accuracy_score(y_test,y_pred1)
acc

0.665625

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
f1=f1_score(y_test,y_pred1,average='weighted')

In [ ]:
f1

0.6492919627039689

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer=SimpleImputer(strategy='median')

In [ ]:
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [ ]:
data["fixed acidity"]=imputer.fit_transform(data[["fixed acidity"]])

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca=PCA()

In [ ]:
x

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [ ]:
pca_data=pca.fit_transform(x)

In [ ]:
pd.DataFrame(pca_data)

,0,1,2,3,4,5,6,7,8,9,10
0,-13.224905,-2.023900,-1.126821,-0.399233,-1.085389,0.198018,0.031547,0.147051,0.006047,0.008585,0.000262
1,22.037724,4.408322,-0.310378,-0.199938,-0.557109,0.301325,0.223874,-0.143165,-0.089312,-0.015483,0.000243
2,7.162673,-2.501461,-0.581868,-0.219069,-0.552934,0.205114,0.136190,-0.058480,-0.084793,-0.005749,0.000346
3,13.430063,-1.951122,2.634040,-1.574059,-0.063806,-0.089092,-0.218923,0.062244,0.006281,0.004586,-0.000747
4,-13.224905,-2.023900,-1.126821,-0.399233,-1.085389,0.198018,0.031547,0.147051,0.006047,0.008585,0.000262
...,...,...,...,...,...,...,...,...,...,...,...
1594,1.129111,16.313102,-1.860069,-0.257109,-0.200974,0.058238,-0.020342,-0.039370,0.019054,0.008953,-0.000058
1595,9.489984,21.627525,-1.986558,-0.027199,0.443711,-0.040335,0.102762,0.015382,0.031433,-0.025658,0.000546
1596,-3.431354,14.271243,-1.750719,0.174652,0.236271,-0.089513,0.078622,-0.026835,-0.020558,-0.016826,0.001028
1597,1.132878,16.316167,-2.134414,-0.235388,-0.519028,-0.015548,0.094561,0.041732,0.128439,-0.023328,-0.000269
1598,-3.874377,3.126348,-1.874149,1.700674,0.104330,-0.400244,-0.161218,-0.090191,0.120132,-0.037690,0.000835

In [ ]:
ex=pca.explained_variance_ratio_

In [ ]:
cum=ex.cumsum()
cum

array([0.94657698, 0.99494528, 0.99753445, 0.99905342, 0.99992697,
       0.99996154, 0.9999809 , 0.99999037, 0.99999878, 1.        ,
       1.        ])

In [ ]:
pca_90=(cum>=90).argmax()+1
pca_90

1

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans=KMeans(n_clusters=3,random_state=42)

In [ ]:
label=kmeans.fit_predict(pca_data)

array([0, 1, 1, ..., 1, 1, 1], dtype=int32)

In [ ]:
from sklearn.metrics import silhouette_score

In [ ]:
sil_score=silhouette_score(pca_data,label)

In [ ]:
silhoute_score

0.5220101372059386

In [ ]:
silhoutte_scores=[]

In [ ]:
for k in range(2,11):
  kmeans=KMeans(n_clusters=k,random_state=42)
  labels=kmeans.fit_predict(inp_data)
  sil_score=silhouette_score(pca_data,labels)
  silhoutte_scores.append(sil_score)

In [ ]:
silhoutte

[0.6034220347321608,
 0.5220101372059386,
 0.48545959739584044,
 0.4406711407130703,
 0.39906238040578484,
 0.3925236846583582,
 0.3810599530341494,
 0.3693028136761402,
 0.3823403965185829]

In [ ]:
max_sil_score = max(sil_score_list)
optimal_k = sil_score_list.index(max_sil_score)
optimal_k

0

In [ ]:
#print()
data'mean radius']=data['mean radius'].fillna(data['mean radius'].mean())

In [ ]:
for i in range(2,11):