In [1]:
! pip install -q kaggle

In [4]:
!mkdir ~/.kaggle
! cp /content/drive/MyDrive/kaggle.json ~/.kaggle/

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [5]:
! chmod 600 ~/.kaggle/kaggle.json

In [6]:
! kaggle datasets list

ref                                                              title                                                size  lastUpdated          downloadCount  voteCount  usabilityRating
---------------------------------------------------------------  --------------------------------------------------  -----  -------------------  -------------  ---------  ---------------
lainguyn123/student-performance-factors                          Student Performance Factors                          94KB  2024-09-02 10:53:57          18322        338  1.0
abdulszz/spotify-most-streamed-songs                             Spotify Most Streamed Songs                          60KB  2024-09-07 18:23:14           5040         63  1.0
owm4096/laptop-prices                                            Laptop Prices                                        25KB  2024-09-09 12:43:01           5584         92  1.0
cameronseamons/electronic-sales-sep2023-sep2024                  Customer purchase behavior - Electronic Sales Data  327KB  2024-09-23 01:54:36           2151         40  1.0
waqi786/remote-work-and-mental-health                            Remote Work & Mental Health 🌍🧠                       93KB  2024-09-22 11:44:29           1971         47  1.0
waqi786/impact-of-virtual-reality-on-education                   Impact of Virtual Reality on Education 📚🕶️           79KB  2024-09-25 11:54:14            960         25  1.0
mexwell/employee-performance-and-productivity-data               👩🏽‍💻 Employee Performance and Productivity Data       2MB  2024-09-04 08:28:04           1575         25  1.0
nyagami/ea-sports-fc-25-database-ratings-and-stats               EA SPORTS FC 25 DATABASE, RATINGS AND STATS           3MB  2024-09-26 08:14:25           1447         31  1.0
taweilo/mba-admission-dataset                                    MBA Admission dataset, Class 2025                    55KB  2024-09-18 07:57:38           2569         45  1.0
mrmars1010/iphone-customer-reviews-nlp                           IPhone Customer Reviews | NLP                       350KB  2024-09-22 02:14:40           1478         27  1.0
iamtanmayshukla/2024-u-s-election-generic-ballot-polling-data    2024 USA Election Polling Data                       25KB  2024-08-20 22:34:30            259        262  1.0
stealthtechnologies/bear-attacks-north-america                   Bear Attacks North America                           20KB  2024-09-17 11:13:51           1706         28  1.0
muhammadehsan02/us-stock-market-and-commodities-data-2020-2024   US Stock Market and Commodities Data (2020-2024)    123KB  2024-09-01 15:00:37           1321         26  1.0
mrsimple07/remote-work-productivity                              Remote Work Productivity                              7KB  2024-09-09 09:36:34           1239         24  1.0
hanaksoy/customer-purchasing-behaviors                           Customer Purchasing Behaviors                         1KB  2024-09-01 22:18:07           6893         83  1.0
zusmani/imran-khans-speeches                                     Imran Khan's Speeches                               298KB  2024-09-26 18:51:09            339         33  1.0
abdullah0a/retail-sales-data-with-seasonal-trends-and-marketing  Retail Sales Data with Seasonal Trends & Marketing  610KB  2024-09-18 16:15:46           4655         61  1.0
stealthtechnologies/predict-people-personality-types             Predict People Personality Types                      4MB  2024-09-14 10:58:11           2088         36  1.0
abdelrahmanemad594/premier-league-season-2024                    Premier League Season 2024                           804B  2024-09-20 12:13:51            798         24  1.0
lorenzozoppelletto/financial-risk-for-loan-approval              Financial Risk for Loan Approval                      2MB  2024-09-07 18:39:43           1983         32  0.9411765

In [13]:
! kaggle competitions download -c problem-5-spaceship

Downloading problem-5-spaceship.zip to /content
  0% 0.00/299k [00:00<?, ?B/s]
100% 299k/299k [00:00<00:00, 93.0MB/s]

In [16]:
!unzip /content/problem-5-spaceship.zip

Archive:  /content/problem-5-spaceship.zip
  inflating: sample_submission.csv
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: test.csv
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: train.csv

In [17]:
import pandas as pd
import numpy as np

In [18]:
train=pd.read_csv("/content/train.csv")

In [19]:
train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [22]:
test=pd.read_csv("/content/test.csv")

In [23]:
test.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [25]:
train.shape,test.shape

((8693, 14), (4277, 13))

In [26]:
train["HomePlanet"].value_counts()

HomePlanet
Earth     4602
Europa    2131
Mars      1759
Name: count, dtype: int64

In [27]:
train["Destination"].value_counts()

Destination
TRAPPIST-1e      5915
55 Cancri e      1800
PSO J318.5-22     796
Name: count, dtype: int64