In [240]:
! pip install -q kaggle

In [241]:
!mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [242]:
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/

In [243]:
! chmod 600 ~/.kaggle/kaggle.json

In [244]:
! kaggle competitions download -c problem2-used-car-price-prediction

problem2-used-car-price-prediction.zip: Skipping, found more recently modified local copy (use --force to force download)

In [245]:
!unzip /content/problem2-used-car-price-prediction.zip

Archive:  /content/problem2-used-car-price-prediction.zip
replace sample_submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: sample_submission.csv
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: test.csv
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: train.csv

In [246]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [247]:
df=pd.read_csv("/content/train.csv")

In [248]:
df.head()

,Id,Mileage,EngineSize,Horsepower,Age,NumberOfDoors,Weight,FuelCapacity,TopSpeed,Acceleration,...,FuelType,Color,Condition,SafetyRating,ComfortRating,TechnologyRating,BrandPopularity,IFeature,RFeature,Price
0,1,44166.12500,1.477207,175.418191,13,2,3951.090535,6.352488,148.548296,10.095521,...,0,1,2,2,1,2,5,-0.814451,175.402641,67840.07026
1,2,50947.97343,0.905297,185.245504,3,4,4529.185652,13.086345,164.255196,6.150027,...,2,2,2,5,5,3,4,0.560742,185.249967,84080.37107
2,3,43809.07121,4.438929,271.568339,12,2,4554.484288,25.594876,118.030078,11.073373,...,0,1,3,2,4,5,2,-0.815535,271.568403,97091.10956
3,4,41348.83624,1.696821,200.168775,16,4,3604.213295,8.481377,119.212560,6.990170,...,0,3,2,1,5,3,5,0.526671,200.174173,67987.03732
4,5,81010.00986,1.356274,295.206830,18,4,4264.749981,12.205729,131.560905,10.606177,...,0,0,2,1,4,1,4,-0.573623,295.200060,97047.28827

In [249]:
df.describe()

,Id,Mileage,EngineSize,Horsepower,Age,NumberOfDoors,Weight,FuelCapacity,TopSpeed,Acceleration,...,FuelType,Color,Condition,SafetyRating,ComfortRating,TechnologyRating,BrandPopularity,IFeature,RFeature,Price
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,...,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,250.500000,61015.442539,2.540802,202.189562,10.428000,3.052000,3489.918421,14.954595,150.220971,7.978518,...,1.004000,2.018000,2.954000,2.926000,2.908000,3.040000,3.116000,0.014623,202.188697,80410.604895
std,144.481833,49843.898927,0.992239,48.763552,5.404001,0.999647,752.743260,5.135341,20.370335,2.079469,...,0.815668,1.414807,1.398498,1.384325,1.382519,1.420717,1.383609,0.997947,48.763724,15939.117566
min,1.000000,-14825.346800,-0.440389,49.024392,1.000000,2.000000,1095.004458,0.676451,94.405862,1.182067,...,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-2.866072,49.028539,24924.087090
25%,125.750000,36691.241515,1.875783,170.281357,6.000000,2.000000,3009.146940,11.067893,135.496012,6.590994,...,0.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,-0.668134,170.273647,69673.391780
50%,250.500000,51684.639270,2.571645,200.533406,11.000000,4.000000,3531.681354,15.076549,149.905583,7.938486,...,1.000000,2.000000,3.000000,3.000000,3.000000,3.000000,3.000000,0.066081,200.521898,81646.994340
75%,375.250000,64229.391670,3.171648,237.083313,15.000000,4.000000,3982.134660,18.774523,165.154493,9.392211,...,2.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,0.675204,237.092962,90373.959795
max,500.000000,246229.828800,5.693108,396.311885,19.000000,4.000000,5653.902870,32.997334,209.217394,14.186859,...,2.000000,4.000000,5.000000,5.000000,5.000000,5.000000,5.000000,2.727328,396.311514,140082.762300

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                500 non-null    int64
 1   Mileage           500 non-null    float64
 2   EngineSize        500 non-null    float64
 3   Horsepower        500 non-null    float64
 4   Age               500 non-null    int64
 5   NumberOfDoors     500 non-null    int64
 6   Weight            500 non-null    float64
 7   FuelCapacity      500 non-null    float64
 8   TopSpeed          500 non-null    float64
 9   Acceleration      500 non-null    float64
 10  Wheelbase         500 non-null    float64
 11  Make              500 non-null    int64
 12  Model             500 non-null    int64
 13  Transmission      500 non-null    int64
 14  FuelType          500 non-null    int64
 15  Color             500 non-null    int64
 16  Condition         500 non-null    int64
 17  SafetyRating      500 non-null    int64
 18  ComfortRating     500 non-null    int64
 19  TechnologyRating  500 non-null    int64
 20  BrandPopularity   500 non-null    int64
 21  IFeature          500 non-null    float64
 22  RFeature          500 non-null    float64
 23  Price             500 non-null    float64
dtypes: float64(11), int64(13)
memory usage: 93.9 KB

In [251]:
train=df.copy()

In [252]:
train

,Id,Mileage,EngineSize,Horsepower,Age,NumberOfDoors,Weight,FuelCapacity,TopSpeed,Acceleration,...,FuelType,Color,Condition,SafetyRating,ComfortRating,TechnologyRating,BrandPopularity,IFeature,RFeature,Price
0,1,44166.12500,1.477207,175.418191,13,2,3951.090535,6.352488,148.548296,10.095521,...,0,1,2,2,1,2,5,-0.814451,175.402641,67840.07026
1,2,50947.97343,0.905297,185.245504,3,4,4529.185652,13.086345,164.255196,6.150027,...,2,2,2,5,5,3,4,0.560742,185.249967,84080.37107
2,3,43809.07121,4.438929,271.568339,12,2,4554.484288,25.594876,118.030078,11.073373,...,0,1,3,2,4,5,2,-0.815535,271.568403,97091.10956
3,4,41348.83624,1.696821,200.168775,16,4,3604.213295,8.481377,119.212560,6.990170,...,0,3,2,1,5,3,5,0.526671,200.174173,67987.03732
4,5,81010.00986,1.356274,295.206830,18,4,4264.749981,12.205729,131.560905,10.606177,...,0,0,2,1,4,1,4,-0.573623,295.200060,97047.28827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,30482.53494,1.845924,176.709722,11,2,3673.578232,14.474696,128.329698,3.308995,...,1,1,1,1,5,2,2,0.887282,176.710375,65644.15545
496,497,54442.67543,2.767127,195.970012,7,4,3621.234567,15.465032,186.937318,8.453638,...,1,3,4,3,2,1,2,-0.755371,195.981589,80493.99774
497,498,53881.79986,2.027909,264.793589,19,4,3445.707015,18.970918,163.196566,8.505135,...,1,2,5,4,3,3,3,-0.565728,264.786143,92591.39311
498,499,49337.46054,3.810309,198.447053,15,2,3688.223992,6.659986,147.740127,7.923552,...,0,0,4,1,1,5,4,-1.175552,198.441343,71713.07958
499,500,38487.24348,4.139965,231.476479,9,4,4617.628308,14.316009,158.836023,8.246889,...,1,3,4,2,3,3,3,-0.053263,231.485274,86575.46146

In [253]:
test=pd.read_csv("/content/test.csv")

In [254]:
test

,Id,Mileage,EngineSize,Horsepower,Age,NumberOfDoors,Weight,FuelCapacity,TopSpeed,Acceleration,...,Transmission,FuelType,Color,Condition,SafetyRating,ComfortRating,TechnologyRating,BrandPopularity,IFeature,RFeature
0,501,56835.11952,3.801741,188.479964,6,2,3756.241546,15.676035,162.643196,9.259340,...,1,2,3,1,5,4,5,2,0.782985,188.493258
1,502,66812.87098,3.155901,131.584248,14,4,3197.661312,22.322568,145.081875,8.156202,...,1,0,1,2,5,1,1,3,-0.778534,131.568912
2,503,33380.99767,3.977530,133.877102,12,2,4111.438465,27.514813,150.016981,6.758564,...,0,0,0,1,4,3,1,5,-0.230726,133.877236
3,504,21397.17244,1.596092,215.982591,18,4,2820.206934,17.105866,146.930873,8.516852,...,1,2,2,5,1,4,4,2,-0.824586,215.987039
4,505,71309.60750,1.512820,103.616371,9,2,4903.849500,19.200835,148.654042,6.917950,...,0,2,0,1,3,3,1,2,-0.681389,103.614481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,717,80760.73133,2.977041,261.806536,17,2,3089.945874,20.537285,139.346820,5.922203,...,0,1,0,3,4,2,5,2,0.054561,261.807753
217,718,87723.71802,3.112774,154.968963,10,4,3588.946515,18.333927,159.746330,6.796996,...,1,2,0,5,4,4,4,5,1.202134,154.958198
218,719,78825.46578,3.591310,217.383824,11,2,2056.826687,13.897915,173.884634,10.674630,...,1,1,2,5,5,2,3,4,0.744691,217.384327
219,720,54058.46042,2.365691,173.439285,8,4,2916.179773,16.918246,127.751296,12.705170,...,1,1,2,4,4,2,4,3,-1.201113,173.440606
220,721,43145.70967,4.588375,156.516846,7,4,4570.245164,8.712914,137.253427,8.873430,...,0,0,2,5,2,5,5,4,1.035893,156.513225

In [255]:
x_sample=train.drop("Price",axis=1)
x_sample=x_sample.drop("Id",axis=1)
y_sample=train["Price"]

In [256]:
x_sample

,Mileage,EngineSize,Horsepower,Age,NumberOfDoors,Weight,FuelCapacity,TopSpeed,Acceleration,Wheelbase,...,Transmission,FuelType,Color,Condition,SafetyRating,ComfortRating,TechnologyRating,BrandPopularity,IFeature,RFeature
0,44166.12500,1.477207,175.418191,13,2,3951.090535,6.352488,148.548296,10.095521,106.560966,...,1,0,1,2,2,1,2,5,-0.814451,175.402641
1,50947.97343,0.905297,185.245504,3,4,4529.185652,13.086345,164.255196,6.150027,112.006852,...,0,2,2,2,5,5,3,4,0.560742,185.249967
2,43809.07121,4.438929,271.568339,12,2,4554.484288,25.594876,118.030078,11.073373,97.607125,...,0,0,1,3,2,4,5,2,-0.815535,271.568403
3,41348.83624,1.696821,200.168775,16,4,3604.213295,8.481377,119.212560,6.990170,101.442649,...,1,0,3,2,1,5,3,5,0.526671,200.174173
4,81010.00986,1.356274,295.206830,18,4,4264.749981,12.205729,131.560905,10.606177,125.193836,...,1,0,0,2,1,4,1,4,-0.573623,295.200060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,30482.53494,1.845924,176.709722,11,2,3673.578232,14.474696,128.329698,3.308995,110.016621,...,1,1,1,1,1,5,2,2,0.887282,176.710375
496,54442.67543,2.767127,195.970012,7,4,3621.234567,15.465032,186.937318,8.453638,101.859629,...,1,1,3,4,3,2,1,2,-0.755371,195.981589
497,53881.79986,2.027909,264.793589,19,4,3445.707015,18.970918,163.196566,8.505135,130.684353,...,0,1,2,5,4,3,3,3,-0.565728,264.786143
498,49337.46054,3.810309,198.447053,15,2,3688.223992,6.659986,147.740127,7.923552,118.646877,...,1,0,0,4,1,1,5,4,-1.175552,198.441343
499,38487.24348,4.139965,231.476479,9,4,4617.628308,14.316009,158.836023,8.246889,96.976337,...,1,1,3,4,2,3,3,3,-0.053263,231.485274

In [257]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [258]:
x_train_sample,x_test_sample,y_train_sample,y_test_sample = train_test_split(x_sample,y_sample,test_size=0.2,random_state=41)

In [259]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None)
lr.fit(x_train_sample,y_train_sample)

LinearRegression()

In [260]:
y_pred_sample =lr.predict(x_test_sample)
print(y_pred_sample)

[ 63840.6487117   67557.22711752  85548.19375142 102060.38953921
  98340.20230891  90578.76727157  99590.78240841  87219.1235216
  89132.77442671  82988.79491639 101701.58877927  64509.82173974
 138532.03022121  86895.48408642  75802.68175389 110189.830652
  68783.56242334  75650.02365683 115170.45722888  82711.08272633
  65775.32153587  84254.52951667  93147.02202389  88924.88933116
  63516.43153166  74321.50096188 105041.96955791  80450.84112233
  90965.17528127  74672.14436201 103089.57787166  79661.48126559
  82201.04075575  67587.50970612  67717.06739435  65478.45397747
  70212.55075656  60140.33320692  64070.86878724  85769.21389326
  53766.17888094  75069.79981031  79707.83970501  84682.29327109
  61422.48393284  96654.13179443  56678.10456989 106864.56790407
  87967.68458723  44306.16060094  93938.87601058  96452.0438516
  82240.9560594   84446.88483842  66642.90102148 103153.84715819
  72167.88558253  74670.93218425  88673.85655316  58143.37299176
  53861.15509745  79964.25873048  96254.18661258  85963.95929169
 105819.3072025   79643.6645061   92200.54501305  54242.17093793
 103812.0842371   71035.87486637  66634.28316744 101383.01859751
 104406.46778913  74907.07269712  96584.66296202  48884.53266842
  89777.69390644  98451.85115481  73210.42624845  60172.15442955
  61467.59720408  88260.64591873  58741.20884439  73494.26710139
  81679.48193492  69637.33637137 114711.20147201  66918.62548198
  53681.74096504  78676.74182256  95343.81118456 111389.73718469
  56629.73970865  73974.63546731  73746.1426402   67705.697453
  67746.46864977  83513.59710319  76269.3850671   75584.12557523]

In [261]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test_sample,y_pred_sample)

982303.8297961674

In [262]:
np.sqrt(mean_squared_error(y_test_sample,y_pred_sample))

991.1124203621744

In [263]:
train

,Id,Mileage,EngineSize,Horsepower,Age,NumberOfDoors,Weight,FuelCapacity,TopSpeed,Acceleration,...,FuelType,Color,Condition,SafetyRating,ComfortRating,TechnologyRating,BrandPopularity,IFeature,RFeature,Price
0,1,44166.12500,1.477207,175.418191,13,2,3951.090535,6.352488,148.548296,10.095521,...,0,1,2,2,1,2,5,-0.814451,175.402641,67840.07026
1,2,50947.97343,0.905297,185.245504,3,4,4529.185652,13.086345,164.255196,6.150027,...,2,2,2,5,5,3,4,0.560742,185.249967,84080.37107
2,3,43809.07121,4.438929,271.568339,12,2,4554.484288,25.594876,118.030078,11.073373,...,0,1,3,2,4,5,2,-0.815535,271.568403,97091.10956
3,4,41348.83624,1.696821,200.168775,16,4,3604.213295,8.481377,119.212560,6.990170,...,0,3,2,1,5,3,5,0.526671,200.174173,67987.03732
4,5,81010.00986,1.356274,295.206830,18,4,4264.749981,12.205729,131.560905,10.606177,...,0,0,2,1,4,1,4,-0.573623,295.200060,97047.28827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,30482.53494,1.845924,176.709722,11,2,3673.578232,14.474696,128.329698,3.308995,...,1,1,1,1,5,2,2,0.887282,176.710375,65644.15545
496,497,54442.67543,2.767127,195.970012,7,4,3621.234567,15.465032,186.937318,8.453638,...,1,3,4,3,2,1,2,-0.755371,195.981589,80493.99774
497,498,53881.79986,2.027909,264.793589,19,4,3445.707015,18.970918,163.196566,8.505135,...,1,2,5,4,3,3,3,-0.565728,264.786143,92591.39311
498,499,49337.46054,3.810309,198.447053,15,2,3688.223992,6.659986,147.740127,7.923552,...,0,0,4,1,1,5,4,-1.175552,198.441343,71713.07958
499,500,38487.24348,4.139965,231.476479,9,4,4617.628308,14.316009,158.836023,8.246889,...,1,3,4,2,3,3,3,-0.053263,231.485274,86575.46146

In [264]:
x_train=train.drop("Price",axis=1).values
y_train=train["Price"].values

In [265]:
x_test=test.copy()

In [266]:
x_test.drop("Id",axis=1,inplace=True)

In [267]:
y_pred=lr.predict(x_test)

In [268]:
y_pred

array([ 85255.74848095,  60095.75557503,  59719.37140461,  70744.95147606,
        52458.53081807,  93229.68869144,  69975.54750734,  72699.80424433,
        87084.25623683,  53275.09732073, 106962.96031321,  33546.76815247,
        93039.68693183,  99567.04442272,  96609.4256254 , 101297.7946097 ,
       107889.67792683,  72775.44528828,  73629.19251645,  68801.72164104,
        73665.89847087,  89556.32951487,  81674.54355945, 103224.68901402,
        45171.02454359,  47940.46551014,  35112.07412445,  95936.98127915,
       101460.45079181,  77086.86307755,  83914.36387344,  64399.56648774,
        96712.54775839, 103307.26820008,  53827.88352209,  61811.10335266,
        76592.26923602,  86898.31150937, 105247.49519654, 124957.08182304,
        60314.94660802,  65131.86940979,  63777.58621264,  65527.58098035,
        42932.87768633,  68324.14094266,  86397.65764427,  58724.14289882,
        65107.28338229, 109019.44890418,  91227.93902845,  87941.65935361,
        89346.76281005, 127024.26124026,  70589.94458973,  94051.29793241,
        72818.79909158,  91097.65279423,  83061.32520586,  73500.44750401,
        78892.02733837,  74043.79591822,  96145.42011913,  78005.77580694,
        91873.49210312, 121795.99989484,  72388.4535235 ,  83835.36763366,
        88315.19764053,  62392.18801984, 106803.9583153 ,  59188.94874038,
        70323.59586955,  71525.41176172,  82858.29705453,  57893.83530659,
        73432.04054193,  45459.38124793,  62477.98562352,  95805.58664355,
        88215.39691337,  93373.97675386,  85345.79321412,  63918.11573673,
        96228.98219691,  86855.2911463 ,  54405.70420575,  70749.07513965,
        87204.41478035,  77191.66873926,  85694.95236664,  71283.02448396,
        92718.67896723,  51984.8423442 ,  71462.27163781,  50962.53475657,
        83558.66596177,  85475.63162852,  78024.79486555, 100643.73522885,
        61364.87949662,  75916.99247563,  72530.8811641 ,  88044.53544393,
       113203.09921573,  89327.30558509, 103740.79543769,  78210.11411617,
       110867.49515773,  69256.51695324,  93173.49767535, 106065.78171739,
        82289.93826763,  63585.36668639,  78647.52825341,  76277.30997994,
        83742.09914769,  85016.09985839,  70855.15949093,  72727.94812913,
        67570.43470436,  83884.44419577,  76743.30030334,  78428.00526009,
        81281.30289554,  99319.62049882, 103424.10570377, 109955.24818853,
       102637.93086187,  96200.11296996, 107010.65120725,  88233.57532339,
        82939.7584178 ,  69480.60391949,  82572.80336898,  73145.71396683,
        72766.20290696,  89387.85318862,  65067.59837585,  82950.93854195,
       104392.11737664,  72825.47112072,  82044.6331344 ,  67865.70560375,
        81099.0156931 ,  68013.9466084 ,  94595.00366748,  95277.42446725,
        71120.93889856,  95667.55836951,  89201.37818065,  65333.37269938,
        67277.54052372,  79589.06415283,  92732.07040159,  78394.73905545,
        82052.56269141,  59578.93257412, 106709.9986451 ,  77545.94546829,
       107511.23282021,  82440.00591271,  91043.03425943,  54569.98120904,
        51230.18625811,  73912.30922364,  76046.63505152,  62089.0235065 ,
        89053.48752533,  86256.32934969,  67488.25096503,  76759.57569207,
        63836.03588722,  76756.2077941 ,  53474.11444669,  66614.85639746,
        58484.13665584,  70898.55749571,  76517.78599873,  59900.45544118,
        79714.84684405,  89489.69849815,  97207.3009198 ,  73343.72559358,
        92634.20476576,  71263.5345099 ,  91043.8397526 ,  74227.91395662,
        63487.08467309,  58230.04186315,  78301.35261776,  75725.88126648,
        91106.91538297,  62703.87086734,  98688.08778485,  84767.89639521,
        66617.0262405 ,  54010.79451301,  65488.51771433,  76640.83481043,
        68845.35924044,  70018.31700886,  94016.20416066,  56410.76573546,
        86504.53948191,  59600.22917283,  86688.33782921,  74627.48478158,
        72562.68121774,  88136.65942223,  72604.25667983,  70229.28797372,
        71046.14545321, 100134.07565822,  81241.34623706,  85449.71409849,
        95429.93207006,  70609.5327593 ,  89979.48634745,  75844.19185262,
        68832.75370075])

In [269]:
y_pred.shape

(221,)

In [270]:
submission_4={'Id': test["Id"],'Price': y_pred}
submission_4=pd.DataFrame(submission_4)
submission_4

      Id         Price
0    501  85255.748481
1    502  60095.755575
2    503  59719.371405
3    504  70744.951476
4    505  52458.530818
..   ...           ...
216  717  95429.932070
217  718  70609.532759
218  719  89979.486347
219  720  75844.191853
220  721  68832.753701

[221 rows x 2 columns]

In [271]:
submission_4.to_csv('submission_4.csv', index=False)

In [272]:
pd.read_csv('submission_4.csv')

      Id         Price
0    501  85255.748481
1    502  60095.755575
2    503  59719.371405
3    504  70744.951476
4    505  52458.530818
..   ...           ...
216  717  95429.932070
217  718  70609.532759
218  719  89979.486347
219  720  75844.191853
220  721  68832.753701

[221 rows x 2 columns]

In [273]:
!kaggle competitions submit -c problem2-used-car-price-prediction -f submission_4.csv -m "Message"

100% 4.76k/4.76k [00:00<00:00, 26.3kB/s]
Successfully submitted to Used Car Price Prediction